//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class addCashCount
    {
        public int cashcount_id { get; set; }
        public string ip { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> cash_date { get; set; }
        public Nullable<int> seq_no { get; set; }
        public Nullable<int> activity_no { get; set; }
        public Nullable<int> type1 { get; set; }
        public Nullable<int> type2 { get; set; }
        public Nullable<int> type3 { get; set; }
        public Nullable<int> type4 { get; set; }
        public Nullable<int> start_index { get; set; }
        public Nullable<int> end_index { get; set; }
    }
}
