//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admBankMenuControl
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string CssClass { get; set; }
        public string IsAdmin { get; set; }
        public string TooltipCss { get; set; }
        public string InputOption { get; set; }
        public Nullable<int> SequenceOrder { get; set; }
    }
}
