//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admCountry
    {
        public int Itbid { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string HomeCountry { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyIso { get; set; }
        public Nullable<int> NumericIso { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
