//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admDataSource
    {
        public int DataSourceId { get; set; }
        public string DataSourceDesc { get; set; }
        public string ConnectionString { get; set; }
        public string Direction { get; set; }
        public string DBMS { get; set; }
    }
}
