//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admDataPullingControl
    {
        public int ItbId { get; set; }
        public Nullable<int> ReconTypeId { get; set; }
        public Nullable<int> ReconLevel { get; set; }
        public string TableName { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LastRecordTimeStamp { get; set; }
        public string LastRecordId { get; set; }
        public Nullable<System.DateTime> LastTransDate { get; set; }
        public Nullable<int> RecordsCount { get; set; }
        public Nullable<System.DateTime> LastTimeMatched { get; set; }
        public Nullable<System.DateTime> FromDateParam { get; set; }
        public Nullable<System.DateTime> ToDateParam { get; set; }
        public Nullable<System.DateTime> PullDate { get; set; }
    }
}
