//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admReconDataSource
    {
        public int ReconDSId { get; set; }
        public string DbMode { get; set; }
        public string SourceName { get; set; }
        public string DatabaseType { get; set; }
        public string ipAddress { get; set; }
        public string PortNumber { get; set; }
        public string DatabaseName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }
    }
}
