//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admStatusItem
    {
        public int ItbId { get; set; }
        public string StatusValue { get; set; }
        public string Status { get; set; }
        public string PaymentProcessing { get; set; }
        public string AdminRecord { get; set; }
        public string ClientRecord { get; set; }
    }
}
