//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admSourceAccount
    {
        public int ItbId { get; set; }
        public Nullable<int> ReconTypeId { get; set; }
        public string AcctNo { get; set; }
        public string AcctType { get; set; }
        public string AcctName { get; set; }
        public string SourceName { get; set; }
        public string FileDirectory { get; set; }
        public string FileType { get; set; }
        public string TableName { get; set; }
        public Nullable<int> DataSourceType { get; set; }
        public Nullable<int> DataSourceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Status { get; set; }
        public string AgentCode { get; set; }
        public string WalletNo { get; set; }
        public string VostroAcctNo { get; set; }
        public string Currency { get; set; }
    }
}
