//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admUserProfile
    {
        public int UserId { get; set; }
        public string LoginId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> EnforcePasswordChange { get; set; }
        public Nullable<bool> IsFirstLogin { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
        public Nullable<bool> MultipleLogin { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastLogoutDate { get; set; }
        public Nullable<bool> LoginStatus { get; set; }
        public string MobileNumber { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> PasswordExpiryDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<int> IsLocked { get; set; }
        public Nullable<int> RoleId { get; set; }
        public byte[] Image { get; set; }
        public string ImagePath { get; set; }
    }
}
