//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfricaWorldTransHistory
    {
        public long ItbId { get; set; }
        public string ConfirmationNo { get; set; }
        public string BookingAgent { get; set; }
        public string IATANo { get; set; }
        public string AfricaWorldUserId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Currency { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> BookedAmount { get; set; }
        public Nullable<decimal> CancelledAmount { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public string MatchingStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateMoved { get; set; }
        public string OrigRefNo { get; set; }
        public string MatchingType { get; set; }
        public Nullable<System.DateTime> DismissedDate { get; set; }
        public Nullable<int> DismissedBy { get; set; }
        public Nullable<System.DateTime> PullDate { get; set; }
        public Nullable<System.DateTime> ReinstatedDate { get; set; }
        public Nullable<int> ReinstatedBy { get; set; }
    }
}
