//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class atm_host
    {
        public int host_data_id { get; set; }
        public string terminal_id { get; set; }
        public string stan { get; set; }
        public string pan { get; set; }
        public string acct_no { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string trans_type { get; set; }
        public string trans_category { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<System.DateTime> host_date { get; set; }
        public string reversal_indicator { get; set; }
        public string unique_field { get; set; }
        public string trans_completed { get; set; }
    }
}
