//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchCounter
    {
        public long ItbId { get; set; }
        public string BatchProcessNo { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
