//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBSAfricaWorldTransError
    {
        public long ItbId { get; set; }
        public string ptId { get; set; }
        public string AcctNo { get; set; }
        public string AcctType { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string DebitCredit { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public string CheckNo { get; set; }
        public string PNR { get; set; }
        public string AgentName { get; set; }
        public string ContactNo { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public string DepositorName { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public string MatchingStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MatchingType { get; set; }
        public string OrigRefNo { get; set; }
        public Nullable<int> ReversalCode { get; set; }
        public Nullable<int> DismissedBy { get; set; }
        public Nullable<System.DateTime> DismissedDate { get; set; }
        public Nullable<System.DateTime> PullDate { get; set; }
        public Nullable<System.DateTime> ReinstatedDate { get; set; }
        public Nullable<int> ReinstatedBy { get; set; }
        public string OriginTracerNo { get; set; }
    }
}
