//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CbsAtmTransaction
    {
        public long CoreBankingId { get; set; }
        public string TerminalId { get; set; }
        public string ReferenceNo { get; set; }
        public string Stan { get; set; }
        public string Pan { get; set; }
        public string AcctNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransType { get; set; }
        public string TransCategory { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string ReversalIndicator { get; set; }
        public string TransCompleted { get; set; }
        public string MatchingStatus { get; set; }
        public string MatchingType { get; set; }
        public string OrigRefNo { get; set; }
        public Nullable<int> ReversalCode { get; set; }
        public Nullable<System.DateTime> DismissedDate { get; set; }
        public Nullable<int> DismissedBy { get; set; }
        public Nullable<System.DateTime> PullDate { get; set; }
        public Nullable<System.DateTime> ReinstatedDate { get; set; }
        public Nullable<int> ReinstatedBy { get; set; }
    }
}
