//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeExemption
    {
        public int ItbId { get; set; }
        public string ChargeCode { get; set; }
        public string Description { get; set; }
        public string ChargeType { get; set; }
        public Nullable<bool> SubjectToTax { get; set; }
        public string CurrencyCode { get; set; }
        public string Menu { get; set; }
        public Nullable<decimal> MorningChargeValue { get; set; }
        public Nullable<bool> TimeBased { get; set; }
        public Nullable<System.TimeSpan> MorningStartTime { get; set; }
        public Nullable<System.TimeSpan> MorningEndTime { get; set; }
        public Nullable<System.TimeSpan> AfternoonStartTime { get; set; }
        public Nullable<System.TimeSpan> AfternoonEndTime { get; set; }
        public Nullable<decimal> AfternoonValue { get; set; }
        public string ProductCode { get; set; }
        public string AccountNo { get; set; }
        public bool FullyExempted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
    }
}
