//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyCode
    {
        public string CrncyCode { get; set; }
        public string CrncyName { get; set; }
        public string Country { get; set; }
        public string localCrncy { get; set; }
        public string status { get; set; }
        public string countrycode { get; set; }
        public Nullable<int> crncyId { get; set; }
        public string Symbol { get; set; }
        public string C1DecdigitName { get; set; }
        public string C2DecdigitName { get; set; }
        public string C3DecdigitName { get; set; }
    }
}
