//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class failed_import
    {
        public int import_id { get; set; }
        public Nullable<int> datasource_id { get; set; }
        public string C_string { get; set; }
        public string C_conStyle { get; set; }
        public Nullable<int> C_status { get; set; }
    }
}
