//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_mapping
    {
        public int mapping_id { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public string dest_object { get; set; }
        public Nullable<int> datasource_id { get; set; }
    }
}
