//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileProcessControl
    {
        public int ItbId { get; set; }
        public Nullable<int> ReconTypeId { get; set; }
        public string FileDirectory { get; set; }
        public string FileName { get; set; }
        public string NameConvention { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
