//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalATM
    {
        public int journal_id { get; set; }
        public string title { get; set; }
        public string ip { get; set; }
        public string terminal_id { get; set; }
        public string stan { get; set; }
        public string pan { get; set; }
        public string acct_no { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string trans_type { get; set; }
        public string trans_category { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public string trans_detail { get; set; }
        public string error { get; set; }
        public string comments { get; set; }
        public string unique_field { get; set; }
        public Nullable<int> trans_status { get; set; }
        public Nullable<int> datasource_id { get; set; }
        public Nullable<decimal> gl_ledger { get; set; }
        public string terminalId { get; set; }
        public string atmip { get; set; }
        public string brand { get; set; }
        public Nullable<System.DateTime> trxn_date { get; set; }
        public string trxn_time { get; set; }
        public string tsn { get; set; }
        public Nullable<double> eventType_id { get; set; }
        public string currencyCode { get; set; }
        public Nullable<double> availBal { get; set; }
        public Nullable<double> ledger { get; set; }
        public Nullable<double> surcharge { get; set; }
        public string accountfrm { get; set; }
        public string accountTo { get; set; }
        public string trxn_status { get; set; }
        public string detail { get; set; }
        public string cassette { get; set; }
        public string errcode { get; set; }
        public string rejectcount { get; set; }
        public string dispensecount { get; set; }
        public string requestcount { get; set; }
        public string remaincount { get; set; }
        public string pickupcount { get; set; }
        public string denomination { get; set; }
        public string jrn_filename { get; set; }
        public Nullable<double> mstate_id { get; set; }
        public Nullable<double> device_stateId { get; set; }
        public Nullable<double> file_down_load_id { get; set; }
        public string TransTimeRange { get; set; }
        public string opCode { get; set; }
        public string takenAmount { get; set; }
    }
}
