//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalTransError
    {
        public long ItbId { get; set; }
        public string TerminalId { get; set; }
        public string ATMIp { get; set; }
        public string Brand { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string TransTime { get; set; }
        public string TransRef { get; set; }
        public string Pan { get; set; }
        public Nullable<double> EventTypeId { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<decimal> AvailBal { get; set; }
        public Nullable<decimal> Ledger { get; set; }
        public Nullable<double> Surcharge { get; set; }
        public string AcctFrom { get; set; }
        public string AcctTo { get; set; }
        public string TransStatus { get; set; }
        public string Cassette { get; set; }
        public string ErrorCode { get; set; }
        public string RejectCount { get; set; }
        public string DispenseCount { get; set; }
        public string RequestCount { get; set; }
        public string RemainCount { get; set; }
        public string PickUpCount { get; set; }
        public string Denomination { get; set; }
        public string JournalfileDirectory { get; set; }
        public Nullable<double> MstateId { get; set; }
        public Nullable<double> DeviceStateId { get; set; }
        public Nullable<double> FileDownloadId { get; set; }
        public string TransTimeRange { get; set; }
        public string OpCode { get; set; }
        public string TakenAmount { get; set; }
        public string MatchingStatus { get; set; }
        public string MatchingType { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public string ErrorMsg { get; set; }
        public string OrigRefNo { get; set; }
        public Nullable<System.DateTime> DismissedDate { get; set; }
        public Nullable<int> DismissedBy { get; set; }
        public Nullable<System.DateTime> PullDate { get; set; }
        public Nullable<System.DateTime> ReinstatedDate { get; set; }
        public Nullable<int> ReinstatedBy { get; set; }
    }
}
