//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaded_dates
    {
        public int loaded_id { get; set; }
        public Nullable<int> datasource_id { get; set; }
        public string date1 { get; set; }
        public string date2 { get; set; }
    }
}
