//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MGTran
    {
        public long ItbId { get; set; }
        public string SettlementCurrency { get; set; }
        public string TransactionCurrency { get; set; }
        public string AccountNo { get; set; }
        public string LegacyID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionId { get; set; }
        public string RefNo { get; set; }
        public string Prod { get; set; }
        public string TransactionType { get; set; }
        public string OrigCountry { get; set; }
        public string RevCountry { get; set; }
        public Nullable<decimal> FXRate { get; set; }
        public Nullable<decimal> FXExchngRate { get; set; }
        public Nullable<System.DateTime> FXDate { get; set; }
        public Nullable<System.DateTime> FxExchangeDate { get; set; }
        public Nullable<decimal> FXMargin { get; set; }
        public string Direction { get; set; }
        public string XchangeDirection { get; set; }
        public Nullable<decimal> BaseAmount { get; set; }
        public Nullable<decimal> ExchangeAmount { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public Nullable<decimal> ExchangeFeeAmount { get; set; }
        public Nullable<decimal> ShareAmount { get; set; }
        public Nullable<decimal> ExchangeShareAmount { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public Nullable<decimal> ExchangeComAmount { get; set; }
        public string MatchingStatus { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MatchingType { get; set; }
        public string FileName { get; set; }
        public string OrigRefNo { get; set; }
        public Nullable<System.DateTime> DismissedDate { get; set; }
        public Nullable<int> DismissedBy { get; set; }
        public Nullable<System.DateTime> PullDate { get; set; }
        public Nullable<System.DateTime> ReinstatedDate { get; set; }
        public Nullable<int> ReinstatedBy { get; set; }
    }
}
