//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTNTransDismisssed
    {
        public long ItbId { get; set; }
        public string TransId { get; set; }
        public string ExternalTransId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Type { get; set; }
        public string ProviderCategory { get; set; }
        public Nullable<int> ToMsg { get; set; }
        public string From { get; set; }
        public string FromName { get; set; }
        public string To { get; set; }
        public string ToName { get; set; }
        public string InitiatedBy { get; set; }
        public string OnBehalfOf { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency1 { get; set; }
        public Nullable<int> Fee { get; set; }
        public string Currency2 { get; set; }
        public string Discount { get; set; }
        public string Currency3 { get; set; }
        public string Promotion { get; set; }
        public string Currency4 { get; set; }
        public string Coupon { get; set; }
        public string Currency5 { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Currency6 { get; set; }
        public string Information { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public string MatchingStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MatchingType { get; set; }
        public string ErrorMsg { get; set; }
        public string FileName { get; set; }
        public string OrigRefNo { get; set; }
        public Nullable<System.DateTime> DismissedDate { get; set; }
        public Nullable<int> DismissedBy { get; set; }
    }
}
