//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettementReport
    {
        public int ItbId { get; set; }
        public System.DateTime Date { get; set; }
        public string Transaction { get; set; }
        public decimal Spread { get; set; }
        public decimal RatesSettle { get; set; }
        public decimal RatesPayout { get; set; }
        public string CurrencyCode { get; set; }
        public decimal SendPrincipal { get; set; }
        public decimal SendCharges { get; set; }
        public decimal SettlementPrincipal { get; set; }
        public decimal SettlementCharges { get; set; }
        public decimal SettlementFX { get; set; }
        public decimal SettlementTotal { get; set; }
    }
}
