//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnityLinkTran
    {
        public long ItbId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string TransRef { get; set; }
        public string TransType { get; set; }
        public string Remitter { get; set; }
        public string Beneficiary { get; set; }
        public Nullable<decimal> SourceAmount { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> DestAmount { get; set; }
        public string ProcessedbyAndDate { get; set; }
        public string MatchingStatus { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MatchingType { get; set; }
        public string FileName { get; set; }
        public string OrigRefNo { get; set; }
        public Nullable<System.DateTime> DismissedDate { get; set; }
        public Nullable<int> DismissedBy { get; set; }
        public string DestCurrency { get; set; }
        public string SourceCurrency { get; set; }
        public Nullable<System.DateTime> PullDate { get; set; }
        public Nullable<System.DateTime> ReinstatedDate { get; set; }
        public Nullable<int> ReinstatedBy { get; set; }
    }
}
