//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class voyager
    {
        public int ItbId { get; set; }
        public string Date { get; set; }
        public string Transaction { get; set; }
        public string Spread { get; set; }
        public string RatesSettle { get; set; }
        public string RatesPayout { get; set; }
        public string CurrencyCode { get; set; }
        public string SendPrincipal { get; set; }
        public string SendCharges { get; set; }
        public string SettlementPrincipal { get; set; }
        public string SettlementCharges { get; set; }
        public string SettlementFX { get; set; }
        public string SettlementTotal { get; set; }
    }
}
