//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WUMTAgentSettlement
    {
        public decimal itbId { get; set; }
        public string ProductType { get; set; }
        public string ProductCode { get; set; }
        public string MTProductName { get; set; }
        public string SettlementInstution { get; set; }
        public string SettlemtInstAddress { get; set; }
        public Nullable<decimal> AdviceNumber { get; set; }
        public Nullable<System.DateTime> AdviceDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string AgentNo { get; set; }
        public string AgentCountry { get; set; }
        public string AgentName { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string BaseCurrency { get; set; }
        public Nullable<decimal> Principal { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<decimal> ForeignExchange { get; set; }
        public Nullable<decimal> SharedCostAdj { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string SettledCurrency { get; set; }
        public Nullable<decimal> SettledPrincipal { get; set; }
        public Nullable<decimal> SettledCharges { get; set; }
        public Nullable<decimal> SettledFX { get; set; }
        public Nullable<decimal> SettledSharedCostAdj { get; set; }
        public Nullable<decimal> SettledTotalAmount { get; set; }
        public Nullable<decimal> WireTransferNumber { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<decimal> ExchgRate { get; set; }
        public Nullable<decimal> RevalRate { get; set; }
        public string status { get; set; }
        public Nullable<decimal> batchno { get; set; }
        public int fileid { get; set; }
    }
}
