//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReconWindowService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WUMTTran
    {
        public long ItbId { get; set; }
        public string AgentCode { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string TransReference { get; set; }
        public Nullable<decimal> Spread { get; set; }
        public Nullable<decimal> SettleRate { get; set; }
        public Nullable<decimal> PayoutRate { get; set; }
        public string SentCurrencyCode { get; set; }
        public Nullable<decimal> SentPrincipal { get; set; }
        public Nullable<decimal> SentCharges { get; set; }
        public Nullable<decimal> SettledPrincipal { get; set; }
        public Nullable<decimal> SettledCharges { get; set; }
        public Nullable<decimal> SettledFx { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string SentCountry { get; set; }
        public Nullable<decimal> LcySettleRate { get; set; }
        public Nullable<decimal> LcyPayoutRate { get; set; }
        public string LcyCurrencyCode { get; set; }
        public Nullable<decimal> LcySettledPrin { get; set; }
        public Nullable<decimal> LcyCharges { get; set; }
        public Nullable<decimal> LcySettledPrincipal { get; set; }
        public Nullable<decimal> LcySettledCharges { get; set; }
        public Nullable<decimal> lcySettledFx { get; set; }
        public Nullable<decimal> lcyTotal { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MatchingStatus { get; set; }
        public string MatchingType { get; set; }
        public string FileName { get; set; }
        public string OrigRefNo { get; set; }
        public Nullable<System.DateTime> DismissedDate { get; set; }
        public Nullable<int> DismissedBy { get; set; }
        public Nullable<System.DateTime> PullDate { get; set; }
        public Nullable<System.DateTime> ReinstatedDate { get; set; }
        public Nullable<int> ReinstatedBy { get; set; }
    }
}
